### ISSUE TITLE
Section Visualization

### ISSUE THREAD

**Issue by subwaystation** [vgteam/graph-genomics-review#35]
Hi @vgteam,

I am very happy that someone is writing that review. I already noted some literature that I was not aware of, yet ;)
I briefly read through the review and now I am trying to give some constructive feedback. I am aware that this is work in progress.

- I am missing ABySS-explorer [https://github.com/bcgsc/ABySS-explorer](https://github.com/bcgsc/ABySS-explorer), [https://ieeexplore.ieee.org/document/5290690](https://ieeexplore.ieee.org/document/5290690) in the set of viz tools.
![image](https://user-images.githubusercontent.com/10184961/68395730-9cfcce80-0170-11ea-88ec-36268cf56cef.png)
- I know MoMI-G [https://github.com/MoMI-G/MoMI-G/](https://github.com/MoMI-G/MoMI-G/), [https://www.biorxiv.org/content/10.1101/540120v2](https://www.biorxiv.org/content/10.1101/540120v2)  makes heavy use of the SequenceTubeMap, but further enhances it. It brings the ability to visualize annotations. And it has several different views of the same data. 
![image](https://user-images.githubusercontent.com/10184961/68395771-b140cb80-0170-11ea-880b-bc8f3220aa45.png)
- There is a paper [https://academic.oup.com/nar/article/47/14/7262/5532290](https://academic.oup.com/nar/article/47/14/7262/5532290) on the visualization and analysis of RNA-Seq assembly graphs. The layout is calculated with the [NGS Graph Generator](https://github.com/systems-immunology-roslin-institute/ngs-graph-generator). They use https://kajeka.com/graphia/ to visualize the graphs. The animations look nice :) 
![image](https://user-images.githubusercontent.com/10184961/68396003-10064500-0171-11ea-909d-6df3dfcb84c8.png)
The question is, how to go from pangenome graphs to RNA-Seq assembly graphs?! I would say, for a more **precise** study of RNA-Seq experiments, one could head for RNA-Seq assembly graphs.

So far from my side for this section, but I only had a brief look at it until now.
I will take a closer look again to give you more valuable feedback.

**Comment by ekg** [comment]
Please feel free to include these via a pull request. But, it must condense
on what is already there. We hope for things to be at a higher level than
they currently are, with more compare and contrast and classification
between the tools

**Comment by subwaystation** [comment]
I will try to keep it as short as possible and put more emphasis on an abstract classification.

I forgot that SWIGG [https://github.com/NCBI-Codeathons/SWIGG](https://github.com/NCBI-Codeathons/SWIGG) can produce visualizations of genome graphs, too.
![image](https://user-images.githubusercontent.com/10184961/68399069-12b76900-0176-11ea-859a-05ac09ec6268.png)

**Comment by subwaystation** [comment]
@ekg What about `odgi viz` here? It has a very unique approach of visualizing such a graph. 
But I have the feeling that the concept is still under development?

**Comment by ekg** [comment]
We can mention it. It's similar to vg viz, which is published in my thesis.

**Comment by subwaystation** [comment]
This is done.
