### ISSUE TITLE
No Section Sharing Pangenome Graphs

### ISSUE THREAD

**Issue by subwaystation** [vgteam/graph-genomics-review#38]
This would be the section I am really unsure if it would fit into the paper.
How can such graphs be shared and / or accessed? Because they will become really huge and not so easy to query. The thing I have in mind would be a short section on Semantic Genome Graphs. Though, this might become a topic in the Future Section?

**Comment by ekg** [comment]
We need to add a section on serialization formats. :+1:

**Comment by subwaystation** [comment]
Would it make sense to introduce GFA1 / GFA2 in this section at the beginning?
Currently we are mentioning them in the viz section, which, as @jeizenga pointed out, is not fitting there.

**Comment by ekg** [comment]
I think the end of the introduction should mention them. I'll work on that
now.
