### ISSUE TITLE
More Graph Tools

### ISSUE THREAD

**Issue by subwaystation** [vgteam/graph-genomics-review#39]
### Building Graphs
- PanTools [https://github.com/Sheikhizadeh/pantools](https://github.com/Sheikhizadeh/pantools), [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6158922/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6158922/)
- TwoPaCo [https://github.com/medvedevgroup/TwoPaCo](https://github.com/medvedevgroup/TwoPaCo), [https://academic.oup.com/bioinformatics/article/33/24/4024/2725383](https://academic.oup.com/bioinformatics/article/33/24/4024/2725383)
- McCortex [https://github.com/mcveanlab/mccortex](https://github.com/mcveanlab/mccortex), [https://www.ncbi.nlm.nih.gov/pubmed/29554215](https://www.ncbi.nlm.nih.gov/pubmed/29554215) and CortexJDK [https://github.com/mcveanlab/CortexJDK](https://github.com/mcveanlab/CortexJDK), [http://europepmc.org/abstract/PPR/PPR85394](http://europepmc.org/abstract/PPR/PPR85394) from McVean's lab.
- LOGAN [https://github.com/TonyBolger/LOGAN](https://github.com/TonyBolger/LOGAN), [https://www.biorxiv.org/content/10.1101/175976v1](https://www.biorxiv.org/content/10.1101/175976v1)

**Comment by subwaystation** [comment]
- REVEAL [https://github.com/jasperlinthorst/reveal](https://github.com/jasperlinthorst/reveal)

**Comment by ekg** [comment]
Bifrost

**Comment by subwaystation** [comment]
- GenGraph (claims to be more usable to the scientific community compared to vg, because of its python implementation).

**Comment by subwaystation** [comment]
As far as I read it, all tools are in the paper now.
