### ISSUE TITLE
is it De Bruijn or de Bruijn graphs?

### ISSUE THREAD

**Issue by ekg** [vgteam/graph-genomics-review#60]
I can't seem to see what the consensus about how to write this is.

I just want it consistent. Any suggestions? I'm leaning towards "De Bruijn graphs".

**Comment by jeizenga** [comment]
I'm partial to small d, since that's how he spelled his name.
https://en.wikipedia.org/wiki/Nicolaas_Govert_de_Bruijn

**Comment by jeizenga** [comment]
We need a Dutch person to tell us how this works. Maybe we can make them a co-author.

**Comment by ekg** [comment]
@JervenBolleman ?

**Comment by JervenBolleman** [comment]
It's with lower case "de" like in English titlecase you don't uppercase
"the".

**Comment by adamnovak** [comment]
I bothered a person who has their own "de" and got lowercase as an answer. I think I put a footnote in the text in favor of lowercase too.
