### ISSUE TITLE
I pulled SHIMMER Sketch Graphs out

### ISSUE THREAD

**Issue by adamnovak** [vgteam/graph-genomics-review#80]
I pulled "SHIMMER Sketch Graphs" out of the table of visualization tools, because I couldn't find a citation or a link for it, and I couldn't work out what to put in the new/different columns I was adding to the table.

@cschin, apparently this is your tool and might be part of https://github.com/cschin/Peregrine perhaps? Can you provide a link/reference for the visualization aspect of the tool?

**Comment by subwaystation** [comment]
As far as I am aware of, the initial source is https://medium.com/@infoecho/constructing-a-graph-for-genome-comparison-swiftly-d47dcd7eae5d. Pointing to script https://gist.github.com/cschin/0584a5ffd57bcf9bf5a970c1a9c580d8 which shows how the visualizations are generated.
But I am not sure how one would integrate this into the paper.

**Comment by ekg** [comment]
It's OK that we don't include this. I suspect it will become well-known as works are published using it. But at the moment it's even more fresh than some things which I felt it might be a stretch to add (minigraph and seqwish for instance).
